version: '3.9'
services:
  database:
    image: postgres:17
    container_name: minecraft
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    command: redis-server --requirepass strongpassword --appendonly yes
